### ISSUE TITLE
Pack update action

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/github-config#167]
There should be an action in this repo that update the version of `pack` that in our is in out script and images that install `pack`, see [here](https://github.com/paketo-buildpacks/github-config/blob/ee020e8e304b3f21fb14c396594235f77425922a/implementation/scripts/.util/tools.sh#L98).

**Comment by floragj** [comment]
For the Full Builder automation, [we use the CNB-distributed pack image](https://github.com/paketo-buildpacks/full-builder/blob/decb615096ca5e5fb7597e506edc0de6e1ab91fb/.github/workflows/test-pull-request.yml#L17). For now, that's pinned to 14.0 due to a bug, but can be easily set to pull in the latest image. Perhaps this is the way to go?

**Comment by sophiewigmore** [comment]
Agreed @floragj this could be a better solution. However, the fact that we're pinned to a version right now because of a bug tells me that we might not want to always just pull in latest. I'm not sure if grabbing the latest is what we want in this case, but neither is having to remember to bump a version by hand.

**Comment by floragj** [comment]
Weird idea: maybe we add a redundancy where we first use the latest version of the pack image for whatever we're doing. And if that fails, we repeat what we were trying to do with a "stable" version (e.g. 14 right now). 

Downsides: adds complexity, increases runtime of some actions
Upsides: we keep dogfooding the latest pack image without manual intervention, we still use a stable image as needed

**Comment by sophiewigmore** [comment]
@floragj The only issue with that would become having to remember to bump whatever the 'stable' version is, unless we implemented even more logic to update the stable version
