### ISSUE TITLE
Tool for automatically updating buildpacks in builder in CI

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/github-config#187]
Hi there! 👋 

We would really like to use your existing tooling for updating buildpack dependencies in our custom builder. Do you have plans to separately publish and support this update tooling? We would prefer to us this instead of creating our own!

https://github.com/paketo-buildpacks/github-config/tree/main/actions/builder/update

Alternatively, it looks like there is a dockerfile for this tool that maybe could be published as an image to the same location as the buildpacks and builders?

**Comment by sophiewigmore** [comment]
Hi @genevieve, we don't currently have plans to separately publish this tooling. This is an interesting idea, I'd be interested to see if other users have a similar needs. I'm not sure how helpful this would be as an image since you'd still need to wire up a Github Actions workflow (like the one in the [builder repos](https://github.com/paketo-buildpacks/full-builder/blob/c5eef30b46d4123dbaf3f4c7d8de159886f0f095/.github/workflows/update-builder-toml.yml#L22)) to use the action?  I will let you know if we decide to separate this out eventually.

**Comment by sophiewigmore** [comment]
@genevieve for now, a hack you could use would be to go into the [`entrypoint`](https://github.com/paketo-buildpacks/github-config/tree/main/actions/builder/update/entrypoint) directory of the action code and run:

` go run main.go --builder-file <path-to-your-builder.toml> --registry-server <registry-server> | sed "s/%0A/\n/g" | sed "s/::set-output name=builder_toml:://g" > /tmp/builder.toml`

It's a bit hacky since it takes care of the extra things we have to add for our workflows, but it will give you an updated builder.toml

**Comment by fg-j** [comment]
With the [latest release of jam](https://github.com/paketo-buildpacks/packit/releases/tag/v0.7.0) you can use `jam update-builder --builder-file builder.toml` to get the latest versions of buildpacks listed in your builder.
