### ISSUE TITLE
create-package tool should only be added to repos that need it

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/github-config#383]
@ForestEckhardt it looks like the action that updates createpackage is adding it to tools.json files that don’t need it.

_Originally posted by @fg-j in https://github.com/paketo-buildpacks/github-config/pull/382#pullrequestreview-822715340_

**Comment by ForestEckhardt** [comment]
I think that the entry is only being added to the tools.json and that doesn't result in the tool itself being installed necessarily.

**Comment by ForestEckhardt** [comment]
Looking into this we also unnecessarily install the `jam` cli in the builder smoke tests.

**Comment by fg-j** [comment]
@ForestEckhardt The buildpackless builders *do* need jam during the smoke tests, because they need to build a version of the Procfile buildpack for testing. (See [this test setup step](https://github.com/paketo-buildpacks/buildpackless-full-builder/blob/ed28687abef06baa4a78bfadc37f254c833f7678/smoke/init_test.go#L47))

**Comment by fg-j** [comment]
I don't think we need `create-package` for the language family buildpacks, though, so it need not be in the language family [tools.json](https://github.com/paketo-buildpacks/github-config/blob/23fbef20028b24aa9efd5959ec826e032a136bc0/language-family/scripts/.util/tools.json#L2).

**Comment by ForestEckhardt** [comment]
And I guess to just call this out we are trying to reduce the number of useless updates being sent to these other repos which is why we want to eliminate this?
